### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by ngoccuong291** [mixu/siobench#1]
Hi Mikito

I have tried to install this benmarking tool, but I failed.
When I tried npm install, it could not get the getrusage and the nodeunit-runner
The same thing happen when I try npm install for sio0617.
Error message:

{{{
npm http GET https://registry.npmjs.org/nodeunit
npm http GET https://registry.npmjs.org/wormhole
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/wormhole
npm http GET https://registry.npmjs.org/wormhole/-/wormhole-3.0.0.tgz
npm http 304 https://registry.npmjs.org/nodeunit
npm http 304 https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nodeunit/-/nodeunit-0.5.5.tgz
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.2.2.tgz
npm ERR! git clone git@github.com:mixu/nodeunit-runner.git Cloning into '/var/folders/x7/d8gwbrhx0dn750hkpmc3cl8h0000gr/T/npm-1336540308552/1336540308560-0.5673553519882262'...
npm ERR! git clone git@github.com:mixu/nodeunit-runner.git 
npm ERR! git clone git@github.com:mixu/nodeunit-runner.git Permission denied (publickey).
npm ERR! git clone git@github.com:mixu/nodeunit-runner.git fatal: The remote end hung up unexpectedly

npm ERR! Error: `git "clone" "git@github.com:mixu/nodeunit-runner.git" "/var/folders/x7/d8gwbrhx0dn750hkpmc3cl8h0000gr/T/npm-1336540308552/1336540308560-0.5673553519882262"` failed with 128
npm ERR!     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/exec.js:49:20)
npm ERR!     at ChildProcess.emit (events.js:70:17)
npm ERR!     at maybeExit (child_process.js:360:16)
npm ERR!     at Process.onexit (child_process.js:396:5)
npm ERR! You may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/myname/Desktop/Draft/siobench
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message `git "clone" "git@github.com:mixu/nodeunit-runner.git" "/var/folders/x7/d8gwbrhx0dn750hkpmc3cl8h0000gr/T/npm-1336540308552/1336540308560-0.5673553519882262"` failed with 128
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/myname/Desktop/Draft/siobench/npm-debug.log
npm not ok
}}}

**Comment by mixu** [comment]
The issue was with the package.json - the git urls were read-write (git+ssh://...), not read only.

Should be fixed now - sorry about that!

**Comment by ngoccuong291** [comment]
Hi Mikito

I tried with the new package.json but another issue came up.

Here is the error message:

{{{
npm http GET https://registry.npmjs.org/nodeunit
npm http GET https://registry.npmjs.org/wormhole
npm http GET https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/nodeunit
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/wormhole
npm http GET https://registry.npmjs.org/nodeunit/-/nodeunit-0.5.5.tgz
npm http GET https://registry.npmjs.org/wormhole/-/wormhole-3.0.0.tgz
npm http GET https://registry.npmjs.org/mkdirp/-/mkdirp-0.2.2.tgz
npm http 200 https://registry.npmjs.org/mkdirp/-/mkdirp-0.2.2.tgz
npm http 200 https://registry.npmjs.org/wormhole/-/wormhole-3.0.0.tgz
npm http 200 https://registry.npmjs.org/nodeunit/-/nodeunit-0.5.5.tgz
npm WARN nodeunit@0.5.5 package.json: bugs['web'] should probably be bugs['url']
npm http GET https://registry.npmjs.org/nodeunit

> getrusage@0.1.3 preinstall /Users/myname/Desktop/Draft/siobench/node_modules/getrusage
> node-waf configure build install

npm http 304 https://registry.npmjs.org/nodeunit
npm http GET https://registry.npmjs.org/nodeunit/-/nodeunit-0.6.4.tgz
Checking for program g++ or c++          : /usr/bin/g++ 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for g++                         : ok  
Checking for node path                   : not found 
Checking for node prefix                 : ok /usr/local 
'configure' finished successfully (0.592s)
Waf: Entering directory `/Users/myname/Desktop/Draft/siobench/node_modules/getrusage/build'
[1/2] cxx: getrusage.cc -> build/Release/getrusage_1.o
../getrusage.cc:6:16: error: ev.h: No such file or directory
npm http 200 https://registry.npmjs.org/nodeunit/-/nodeunit-0.6.4.tgz
Waf: Leaving directory`/Users/myname/Desktop/Draft/siobench/node_modules/getrusage/build'
Build failed:  -> task failed (err #1): 
    {task: cxx getrusage.cc -> getrusage_1.o}
npm ERR! error installing getrusage@0.1.3

npm ERR! getrusage@0.1.3 preinstall: `node-waf configure build install`
npm ERR! `sh "-c" "node-waf configure build install"` failed with 1
npm ERR! 
npm ERR! Failed at the getrusage@0.1.3 preinstall script.
npm ERR! This is most likely a problem with the getrusage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-waf configure build install
npm ERR! You can get their info via:
npm ERR!     npm owner ls getrusage
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Darwin 11.3.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/myname/Desktop/Draft/siobench
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message getrusage@0.1.3 preinstall: `node-waf configure build install`
npm ERR! message `sh "-c" "node-waf configure build install"` failed with 1
npm ERR! errno {}
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/myname/Desktop/Draft/siobench/npm-debug.log
npm not ok
}}}

Here is the log file:
http://www.mediafire.com/?y5h63t6sz55seam

**Comment by mixu** [comment]
Looks like a reference to ev.h in node-getrusage (which is the native extension providing CPU info) is not getting resolved. I think at the time I wrote getrusage libuv was still a WIP so I included ev.h directly.

Anyway, it's not needed anymore, I removed the reference.

To make sure you get a fresh copy of node-getrusage, rm -rf ./node_modules and only then run npm install. I just pushed a fix to mixu/node-getrusage.

**Comment by ngoccuong291** [comment]
Hi Mikito

Thanks so much, it works now. However, I'm not sure if I got it right. I ran the Benchmark using "node siobench.js 0.8.7" but all I got is a long line of messages saying "act1". I read the code, it means that the client was waiting. Have I done anything wrong?

I have gone aroung and found this tool: https://github.com/joshfire/socket.io-loadtest
Is your code trying to do the same thing?

Kind regards

**Comment by mixu** [comment]
Yes, it does similar things but with better instrumentation e.g. it tracks memory and cpu usage at the same time, supports automatically launching parallel clients to generate load until saturation is reached and creates plottable output files etc. 

I haven't updated the code in 6 months which is an eternity in Socket.io terms. As I recall it generates gnuplot-compatible files from each run (e.g. https://github.com/mixu/siobench/blob/master/environments.js ), which can then be plotted using plot.sh (from data generated in subdirectories under "./results/" using https://github.com/mixu/siobench/blob/master/results/plot.sh

which generates images for the runs that are shown in https://github.com/mixu/siobench/blob/master/results/index.html

Anyway, that's how it used to work. You might need to peek under the code and update it a bit for your purposes. BTW Socket.io and Engine.io are awesome.

**Comment by ngoccuong291** [comment]
Cool, I will try to tweak it around a little bit then. Thanks :D
